export const defaultTasksData = [
  {
    id: 1,
    text: "Cortar cebolla",
    completed: false,
    haveRange: false,
    initDate: null,
    endDate: null,
    description: "lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    color: "#9c27b0",
  },
  {
    id: 2,
    text: "Tomar el curso de intro a React",
    completed: false,
    haveRange: true,
    initDate: "2021-08-01",
    endDate: "2021-08-31",
    description: null,
    color: "#03a9f4",
  },
  {
    id: 3,
    text: "Tomar el curso de intro a React",
    completed: false,
    haveRange: true,
    initDate: "2020-01-01",
    endDate: "2020-02-15",
    description: "lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    color: "#ff5722",
  },
  {
    id: 4,
    text: "Probando border",
    completed: false,
    haveRange: true,
    initDate: "2020-02-01",
    endDate: "2020-06-15",
    description: "lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    prioritary: true,
    color: "#3f51b5",
  },
  {
    id: 5,
    text: "Probando complete",
    completed: true,
    haveRange: false,
    initDate: "2020-01-01",
    endDate: "2020-02-15",
    description: "lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    prioritary: true,
    color: "#f44336",
  },
];
